source 'http://rubygems.org'

gem 'rails',         '~>3.0.3'
gem 'haml',          :require => 'haml'
gem 'sqlite3'
gem 'heroku'
gem 'nokogiri'
gem 'jquery-rails'
gem 'uuid'
gem 'rabl'
gem 'rdiscount'
gem 'bundler'
gem 'version'

group :development, :test do
  gem 'rspec-rails'
  gem 'machinist'
  gem 'faker'
  gem 'shoulda'
  gem 'pry-rails'
#  gem 'thin'
#  gem 'ruby-debug19', :require => 'ruby-debug'
#  gem 'hpricot'
#  gem 'ruby_parser'
end
